name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Analyze the code with ruff
      run: |
        ruff check py4phi/
        ruff check cli/
    - name: Analyze the tests with ruff
      run: |    
        ruff check --config ruff-test.toml tests/
    - name: Run tests
      run: |
        pytest ./tests/ --log-disable py4phi_logger --cov=./py4phi/ --cov-fail-under=90
